Add JSON config compatibility and possible options for CMake
MichaelBrim/tedium pull request #2
Opened 2024-10-09 15:12 UTC by SamHerts

Added the library nanojsonc since it is c99 compatible and event driven, to match the ini.h functions.
Added a CMakeLists.txt to Configurator to show possible options for automated installation of ini.h, tinyexpr, and nanojsonc.

2024-10-09 17:39 UTC, MichaelBrim requested changes
Overall, looks good. See specific comments for things to address. When everything is resolved, please squash into one commit.

2024-10-09 17:39 UTC, MichaelBrim commented on configurator/configurator.c
> +    char* ext = strrchr(file, '.') + 1;
when filename does not include a '.' `strrchr()` may return NULL/0, leading to bad ext pointer value

2024-10-09 17:39 UTC, MichaelBrim commented on configurator/configurator.c
> +    // Move to the end of the file to get its size
`fseek(END)+ftell()+fseek(BEGIN)` is way more complicated than just calling `stat()` to get the file size

2024-10-09 17:39 UTC, MichaelBrim commented on configurator/configurator.c
> +    char* simple_section = strdup(section);
all these string dups are being leaked

2024-10-09 17:39 UTC, MichaelBrim commented on configurator/configurator.c
> +    if(simple_section)
I understand why this is sufficient, but I would prefer if there was also a NULL check on `section` that precedes the dup

2024-10-09 18:27 UTC, SamHerts commented on configurator/configurator.c
> +    // Move to the end of the file to get its size
Ah, didn't realize you already had sys/stat included.

2024-10-09 18:51 UTC, SamHerts commented
Changes made and commits squashed.

2024-10-09 19:18 UTC, MichaelBrim commented on configurator/configurator.c
> +        case -1:
something weird going on with the switch case indents, here and below in `json_error_handler`

2024-10-10 13:17 UTC, SamHerts commented on configurator/configurator.c
> +        case -1:
IDE must have messed with the indents

2024-10-11 12:32 UTC, MichaelBrim approved these changes
Looks good. I'll merge soon

2024-10-11 12:33 UTC, merged